* [#A] Week 1 - Getting Orientated to Scrum and CP3405               :ATTACH:
DEADLINE: <2026-09-14 Mon>
:PROPERTIES:
:ID:       e170e307-e8cd-4ef1-bd0c-3e0527b5c192
:END:

** Scrum Learning Notebook
1. Knowledge Check - Based on your previous studies or experience what factors contribute
   to the diffuculty in planning and successfully delivering software projects?

   **Doing a bit everyday**
   Even if its writing a little bit of code, maybe a line or two, still keeps it in the
   forefront of my mind.
   Even if i dont feel like doing any at all, just thinking of it can change my mind
   and it goes from not feeling like doing anything at all today too implementing
   whatever inspired the session.

   **External Reasearch**
   Reading about it after the sessions, looking at others examples and even logging my feelings after the fact provide an outside perspective of the problem at hand.
   Blogs and medium articles have provided countless bursts of inspiration, especially reading not near my computer,unable to do anything but note down the Euraka moment.
   
   **Enjoyable Working Environment**
   Clean desk, near a window with the breeze flowing through.

   **Knowing if you are asking the right questions**
   Not just for the specific problems that may arise during a coding session but sometimes of the project itself.

   **Defined end goal**
   It's great to have a clear, concrete vision of what the project should appear as, however that contains it's own risks where the tunnel vision might cloud out potential avenues     that might be more enriching.

   **User's**
   It's hard to consider all of the potential users of the product. What they want to acheive out of the product, their skill level, patience, time and their approach. It's hard to think of all the possible edge cases of all the users. 
   

** Ai Conversation Reflection
Work through AI conversations. Reflect on;
*what ways did this conversation advance your understanding of the topic?*
Focus on what suprised you, challenged assumptions, or helped you think differently?




** Micro Reflection (Gibbs-style)
Capture one early learning experience from this week.
Few sentences using a simplified Gibbs Cycle (What happened, what noticed or learned, what might do differently) is sufficent.


** Class

